jwtSecret: "develop_key"

database:
  user: "root"
  password: "w772475791"
  host: "127.0.0.1"
  port: 3306
  dbname: "pi"
  charset: "utf8mb4"

aliyun:
  accessKeyId: LTAI5tLJFaEWVAsDgpZ4GME3
  accessKeySecret: WKEuCadUzteO39FhLc0YyilXWjmw9b
  endpoint: oss-cn-wuhan-lr.aliyuncs.com
  bucketName: markdown-wky
  filePath: img_project

